import{a as b,S as w,i as r}from"./assets/vendor-f144e563.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const L="https://pixabay.com/api/",S="44072019-b0f3ca2d34d486b30651cffe6";async function m(t,s=1){const i={key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15},{data:l}=await b.get(L,{params:i});return l}function g(t){return t.map(({webformatURL:s,largeImageURL:i,tags:l,likes:e,views:o,comments:c,downloads:h})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${s}" alt="${l}" />
        </a>
        <div class="info">
          <p class="info-title">Likes: <span class="info-span">${e}</span></p>
          <p class="info-title">Views: <span class="info-span">${o}</span></p>
          <p class="info-title">Comments: <span class="info-span">${c}</span></p>
          <p class="info-title">Downloads: <span class="info-span">${h}</span></p>
        </div>
      </li>`).join("")}const q=document.querySelector(".form"),v=document.querySelector(".input"),p=document.querySelector(".gallery"),R=document.querySelector(".loader2"),n=document.querySelector(".load-more");n&&n.classList.add("load-more-hidden");let a=1,d="",u=0;const y=new w(".gallery a");q.addEventListener("submit",$);n.addEventListener("click",M);function f(t){R.style.display=t}f("none");async function $(t){if(t.preventDefault(),d=v.value.trim(),d===""){r.warning({title:"Warning",message:"Please enter a search term!",position:"topRight",timeout:2e3});return}p.innerHTML="",a=1,f("block");const s=await m(d,a);try{if(s.hits.length===0){r.warning({title:"Warning",message:"No images found. Try another search!",position:"topRight",timeout:2e3});return}p.innerHTML=g(s.hits),y.refresh(),r.success({title:"Success",message:"Images loaded successfully!",position:"topRight",timeout:2e3}),u=Math.ceil(s.totalHits/15),a<u?n.style.display="block":n.style.display="none"}catch(i){r.error({title:"Error",message:`Something went wrong: ${i.message}`,position:"topRight",timeout:2e3}),console.error(i)}finally{f("none")}}async function M(){a+=1,console.log(a),n.disabled=!0;try{const t=await m(d,a);if(t.hits.length===0){n.style.display="none",r.info({title:"Info",message:"No more images to load.",position:"topRight",timeout:2e3});return}p.insertAdjacentHTML("beforeend",g(t.hits)),y.refresh(),a>=u&&(n.style.display="none",r.info({title:"Info",message:"No more images to load.",position:"topRight",timeout:2e3}));const i=document.querySelector(".gallery-item").getBoundingClientRect().height*3;window.scrollBy({left:0,top:i,behavior:"smooth"})}catch(t){n.style.display="none",r.error({title:"Error",message:`Something went wrong: ${t.message}`,position:"topRight",timeout:2e3})}finally{n.disabled=!1}}
//# sourceMappingURL=commonHelpers.js.map
