import{a as y,i as l,S as h}from"./assets/vendor-f144e563.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const w="https://pixabay.com/api/",b="44072019-b0f3ca2d34d486b30651cffe6";async function p(r,o=1){const i={key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};try{const s=await y.get(w,{params:i});if(s.status!==200)throw l.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3}),new Error(s.statusText);const e=s.data;return console.log(e),e}catch(s){l.show({title:"Error",message:"An error occurred while fetching data. Please try again!",position:"topRight",timeout:2e3}),console.error(s)}}function f(r){return r.map(({webformatURL:o,largeImageURL:i,tags:s,likes:e,views:t,comments:c,downloads:m})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${o}" alt="${s}" />
        </a>
        <div class="info">
          <p class="info-title">Likes: <span class="info-span">${e}</span></p>
          <p class="info-title">Views: <span class="info-span">${t}</span></p>
          <p class="info-title">Comments: <span class="info-span">${c}</span></p>
          <p class="info-title">Downloads: <span class="info-span">${m}</span></p>
        </div>
      </li>`).join("")}const L=document.querySelector(".form"),S=document.querySelector(".input"),u=document.querySelector(".gallery"),q=document.querySelector(".loader2"),n=document.querySelector(".load-more");n&&n.classList.add("load-more-hidden");let a=1,E="";const g=new h(".gallery a");L.addEventListener("submit",v);n.addEventListener("click",P);function d(r){q.style.display=r}d("none");async function v(r){r.preventDefault();const o=S.value.trim();if(o==="")return;u.innerHTML="",a=1,d("block");const i=await p(o,a);try{if(i.hits.length===0){l.warning({title:"Warning",message:"No images found. Try another search!",position:"topRight",timeout:2e3});return}u.innerHTML=f(i.hits),g.refresh(),l.success({title:"Success",message:"Images loaded successfully!",position:"topRight",timeout:2e3}),a<i.totalHits&&(n.style.display="block"),i.totalHits<15&&(n.style.display="none")}catch{l.error({title:"Error",message:`Something went wrong: ${error.message}`,position:"topRight",timeout:2e3}),console.error(error)}finally{d("none")}}async function P(){a+=1,console.log(a),n.disabled=!0;try{const r=await p(E,a);u.insertAdjacentHTML("beforeend",f(r.hits)),g.refresh();const o=Math.ceil(r.totalHits/15);a>=o&&(n.style.display="none",l.info({title:"Info",message:"No more images to load.",position:"topRight",timeout:2e3}));const s=document.querySelector(".gallery-item").getBoundingClientRect().height*3;window.scrollBy({left:0,top:s,behavior:"smooth"})}catch{l.error({title:"Error",message:`Something went wrong: ${error.message}`,position:"topRight",timeout:2e3})}finally{n.disabled=!1}}
//# sourceMappingURL=commonHelpers.js.map
