import{a as h,i as n,S as y}from"./assets/vendor-f144e563.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const w="https://pixabay.com/api/",b="44072019-b0f3ca2d34d486b30651cffe6";async function d(i,s=1){const t={key:b,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15};try{const r=await h.get(w,{params:t});if(r.status!==200)throw n.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3}),new Error(r.statusText);const e=r.data;return console.log(e),e}catch(r){n.show({title:"Error",message:"An error occurred while fetching data. Please try again!",position:"topRight",timeout:2e3}),console.error(r)}}function f(i){return i.map(({webformatURL:s,largeImageURL:t,tags:r,likes:e,views:o,comments:c,downloads:g})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${t}">
          <img class="gallery-image" src="${s}" alt="${r}" />
        </a>
        <div class="info">
          <p class="info-title">Likes: <span class="info-span">${e}</span></p>
          <p class="info-title">Views: <span class="info-span">${o}</span></p>
          <p class="info-title">Comments: <span class="info-span">${c}</span></p>
          <p class="info-title">Downloads: <span class="info-span">${g}</span></p>
        </div>
      </li>`).join("")}const L=document.querySelector(".form"),S=document.querySelector(".input"),u=document.querySelector(".gallery"),q=document.querySelector(".loader2"),l=document.querySelector(".load-more");l&&l.classList.add("load-more-hidden");let a=1,E="";const m=new y(".gallery a");L.addEventListener("submit",R);l.addEventListener("click",v);function p(i){q.style.display=i}p("none");function R(i){i.preventDefault();const s=S.value.trim();s!==""&&(u.innerHTML="",a=1,p("block"),d(s,a).then(t=>{if(t.hits.length===0){n.warning({title:"Warning",message:"No images found. Try another search!",position:"topRight",timeout:2e3});return}u.innerHTML=f(t.hits),m.refresh(),n.success({title:"Success",message:"Images loaded successfully!",position:"topRight",timeout:2e3}),a<t.totalHits&&(l.style.display="block",n.info({title:"Info",message:"No more images to load.",position:"topRight",timeout:2e3}))}).catch(t=>{n.error({title:"Error",message:`Something went wrong: ${t.message}`,position:"topRight",timeout:2e3}),console.error(t)}).finally(()=>{p("none")}))}async function v(){a+=1,console.log(a),l.disabled=!0;try{const i=await d(E,a);u.insertAdjacentHTML("beforeend",f(i.hits)),m.refresh();const s=Math.ceil(i.totalHits/15);a>=s&&(l.style.display="none",n.info({title:"Info",message:"No more images to load.",position:"topRight",timeout:2e3}));const r=document.querySelector(".gallery-item").getBoundingClientRect().height*3;window.scrollBy({left:0,top:r,behavior:"smooth"})}catch{n.error({title:"Error",message:`Something went wrong: ${error.message}`,position:"topRight",timeout:2e3})}finally{l.disabled=!1}}
//# sourceMappingURL=commonHelpers.js.map
